### ISSUE TITLE
Cancel previous workflows when there's a new commit

### ISSUE THREAD

**Issue by etiennebacher** [easystats/workflows#28]
I often push commits one by one in PRs and if I forget to add `[skip ci]` then I have to wait a long time to get the results of GHA for the latest commit. I think it's possible to use [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) to cancel the previous workflow with the same name when there's a new commit triggering this workflow.

Is it something that would make sense?

**Comment by IndrajeetPatil** [comment]
I had been meaning to do this. Thanks for providing the impetus!

Let's see if it works as expected.

**Comment by IndrajeetPatil** [comment]
The only annoying thing now is the horde of emails one gets for all cancelled workflows.

**Comment by etiennebacher** [comment]
Yes, it's discussed [here](https://github.com/community/community/discussions/13015) but I don't think there's a solution for now.
