### ISSUE TITLE
Why is `check-readme` workflow failing?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/workflows#32]
Haven't looked closely at it, but I am fairly certain that there is a circularity in the development versions needed.

E.g. parameters requires devel-_see_, while devel-_see_ requires devel-_parameters_, so a new installation process starts while the previous installation task is in progress.

**Comment by IndrajeetPatil** [comment]
There is nothing wrong with this workflow. E.g. it works just fine for [easystats](https://github.com/easystats/easystats/actions/runs/4449881823/jobs/7814648833).

I think once we make new releases and remove circular devel-dependencies, this issue will fix itself.

**Comment by strengejacke** [comment]
That's cool! Helpful to coordinate changes across packages that might cause (rev-)dep issues among our dev-versions. :-)

**Comment by IndrajeetPatil** [comment]
True. But this will start working only from tomorrow. The _pak_ binaries are updated at night.
