### ISSUE TITLE
Ignore archived packages?

### ISSUE THREAD

**Issue by strengejacke** [easystats/workflows#40]
@IndrajeetPatil Pkg _panelr_ was archived on CRAN, and that _might_ be a reason why this workflow fails (https://github.com/easystats/datawizard/actions/runs/5326897717/jobs/9649554277) - I guess the source is _parameters_ or _insight_. Can we somehow ignore missing packages?

**Comment by IndrajeetPatil** [comment]
Unfortunately, currently, we need to do this manually and there is no automated solution. 

That said, maybe `{pak}` / `{pkgdepends}` might implement this at some point if someone requests it.

**Comment by strengejacke** [comment]
Thanks for the quick fix! This is a more or less temporary issue, as I'm removing archived/removed CRAN packages from tests (moving the files into the WIP folder).

I'll probably open issues at the _pak_ or _pkgdepens_ repos, so maybe there's an automatic way of handling this in the future.

**Comment by IndrajeetPatil** [comment]
> Thanks for the quick fix! This is a more or less temporary issue, as I'm removing archived/removed CRAN packages from tests (moving the files into the WIP folder).

I don't think you need to do that. We have made sure that all tests, examples, vignettes, etc. are run conditionally on the packages in question being available. So a package getting archived on CRAN shouldn't cause any problems.

**Comment by strengejacke** [comment]
>  So a package getting archived on CRAN shouldn't cause any problems.

No, not on CRAN - except the NOTES you get ;-)
In the past, I've added back tests once packages return to CRAN (which is not always the case...)
