### ISSUE TITLE
Introduce a workflow to remind maintainers to use the latest easystats deps?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/workflows#43]
E.g., to remind doing something like https://github.com/easystats/modelbased/commit/f15fe8441170346df862a206c5581648fadb17ed, when relevant.

Otherwise, we can go a long time without doing this and the users may also not upgrade to the latest easystats deps because we don't require them to and miss out the best and the latest. This is relevant only until we make stable releases (`1.0.0`), since afterwards all changes will be gradual, and it's not necessary for users to always use the latest easystats deps.

WDYT?

**Comment by IndrajeetPatil** [comment]
@mattansb, @rempsyc, @etiennebacher Please "Watch" this repo because all changes here affect _all_ repositories in our organization.

**Comment by strengejacke** [comment]
Sounds good to me and I think this makes sense!

**Comment by IndrajeetPatil** [comment]
The workflow will run once a 
month and will make a PR if there are new versions.
