### ISSUE TITLE
Specify changes to linter defaults in the GHA itself

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/workflows#5]
Instead of including `.lintr` in every repo in the organization and keeping them all in sync with each other.

**Comment by IndrajeetPatil** [comment]
Works, so `.lintr` in every repo in the organization should be deleted.

**Comment by strengejacke** [comment]
The lintr files are also used by vscode, that's why I primarily added them

**Comment by IndrajeetPatil** [comment]
What do you mean, they are "used by" VS Code? Does VS Code lint every time you make any change to the source code?

I'd prefer if we rely on GHA for this so that everyone is on the same page. Additionally, GHA uses the latest _lintr_ from GitHub, so we are always up-to-date.

**Comment by strengejacke** [comment]
If you don't have a `.lintr` file, the defaults are used. But maybe I can also define defaults globally, not workspace specific.

**Comment by IndrajeetPatil** [comment]
Closing this since it is already implemented.

@strengejacke Okay, I won't delete the `.lintr` files, but make sure to check in on this action once in a while to see which defaults we are choosing and syncing the local file with those settings.

https://github.com/easystats/workflows/blob/db1b951367207b5b9bb45d29f97107466fde9c86/.github/workflows/lint.yaml#L31-L43
